# Generated by Django 6.0.7 on 2026-07-29 23:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('vista', 'Cuenta Vista'), ('ahorro', 'Cuenta de Ahorro'), ('corriente', 'Cuenta Corriente')], default='vista', max_length=15)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.profile')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
