# Generated by Django 6.0.7 on 2026-07-29 23:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.BigIntegerField(default=0)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=11.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_boxes', to='users.profile')),
            ],
            options={
                'verbose_name': 'Cajita',
                'verbose_name_plural': 'Cajitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsBoxInterestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('interest_earned', models.BigIntegerField()),
                ('balance_before', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_logs', to='savings.savingsbox')),
            ],
            options={
                'verbose_name': 'Registro de Interés',
                'verbose_name_plural': 'Registros de Interés',
                'ordering': ['-period_end'],
            },
        ),
    ]
