# Generated by Django 6.0.7 on 2026-07-29 23:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=50)),
                ('card_type', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito')], default='credit', max_length=10)),
                ('last_four', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('credit_limit', models.BigIntegerField()),
                ('used_amount', models.BigIntegerField(default=0)),
                ('expiry_date', models.CharField(max_length=5)),
                ('card_network', models.CharField(default='Visa', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('locked', 'Bloqueada'), ('cancelled', 'Cancelada')], default='active', max_length=10)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='users.profile')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=100)),
                ('total_amount', models.BigIntegerField()),
                ('remaining', models.BigIntegerField()),
                ('monthly_fee', models.BigIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=1.15, max_digits=5)),
                ('total_quotas', models.IntegerField()),
                ('paid_quotas', models.IntegerField(default=0)),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paid', 'Pagado'), ('defaulted', 'En mora')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.profile')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['-created_at'],
            },
        ),
    ]
